---
title: "Plots like collaborations"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile),'/README.md')) })
output: github_document
---

<i>Plots for papers without context</i>

This github will be about plots, figures, charts, foresplot and so on. All of these are part of collaboration with friends like [Oscar J. Ponce](https://twitter.com/PonceOJ), ...



```{r setup, include=FALSE}
library(forestploter)
library(openxlsx)
library(rmarkdown)
knitr::opts_chunk$set(fig.path = "Figures/", dev='svg')
```
<br>
<details>

<summary><b>Figure 1 -</b> Figure about two different models NLP by Oscar and me</summary>

<br>

```{r fig, echo=FALSE, fig.height=5, fig.width=17, message=FALSE, warning=FALSE}
data <- read.xlsx("results_for_graph.xlsx")
data$` ` <- paste(rep("                                 ", nrow(data)))
colnames(data) <- c("outcome", "ca_method", "model", "mean", "low", "up", "p_value", '')
na_row <- data.frame('','', '','','','','','', '')
data$mean_ic <- paste0(data$mean, " (", data$low, " to ", data$up, ")")
colnames(na_row) <- c("outcome", "ca_method", "model", "mean", "low", "up", 
                      "p_value", '', 'mean_ic')
data <- rbind(data[c(1:5),-1], na_row[,-1], data[c(6:10),-1])
tm <- forest_theme(ci_pch = 19)
data$mean <- as.numeric(data$mean)
data$low <- as.numeric(data$low)
data$up <- as.numeric(data$up)
library('stringr')
data$mean_ic <- gsub('(', '[', data$mean_ic, fixed = T)
data$mean_ic <- gsub(')', ']', data$mean_ic, fixed = T)
colnames(data) <- c("CA Method", "Model", "mean", "low", "up", "p_value", '', "Mean [95%CI]")

p <- forest(data[,c(1:2, 7:8)],
               est = data$mean,
               lower = data$low, 
               upper = data$up, 
               sizes = 1,
               ci_column = 3,
               ref_line = 0, 
               xlim = NULL,
               ticks_at = NULL,
            theme = tm)
plot <- plot(p)
```

</details>